version: '3'

networks:
  frontend:
    driver: ${NETWORKS_DRIVER}
  backend:
    driver: ${NETWORKS_DRIVER}

services:

### Workspace Utilities ##################################
    workspace:
      image: r.cfcr.io/lanphan/magento2_workspace:1.0
      restart: unless-stopped
      volumes:
        - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
      extra_hosts:
        - "dockerhost:${DOCKER_HOST_IP}"
      ports:
        - "${WORKSPACE_SSH_PORT}:22"
      tty: true
      networks:
        - frontend
        - backend

### PHP-FPM ##############################################
    php-fpm:
      image: r.cfcr.io/lanphan/magento2_php-fpm:1.0
      restart: unless-stopped
      volumes:
        - ./php-fpm/php${PHP_VERSION}.ini:/usr/local/etc/php/php.ini
        - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
      expose:
        - "9000"
      extra_hosts:
        - "dockerhost:${DOCKER_HOST_IP}"
      depends_on:
        - workspace
      networks:
        - backend

### NGINX Server #########################################
    nginx:
      image: r.cfcr.io/lanphan/magento2_nginx:1.0
      restart: unless-stopped
      volumes:
        - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
        - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
        - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
        - ${NGINX_SSL_PATH}:/etc/nginx/ssl
      ports:
        - "${NGINX_HOST_HTTP_PORT}:80"
        - "${NGINX_HOST_HTTPS_PORT}:443"
      depends_on:
        - php-fpm
      networks:
        - frontend
        - backend

### MySQL ################################################
    mysql_magento2:
      image: r.cfcr.io/lanphan/magento2_mysql:1.0
      environment:
        - MYSQL_DATABASE=${MYSQL_DATABASE_MAGENTO2}
        - MYSQL_USER=${MYSQL_USER_MAGENTO2}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD_MAGENTO2}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD_MAGENTO2}
        - TZ=${WORKSPACE_TIMEZONE}
      volumes:
        - ${DATA_PATH_HOST}/mysql:/var/lib/mysql
        - ${MYSQL_ENTRYPOINT_INITDB_MAGENTO2}:/docker-entrypoint-initdb.d
      ports:
        - "${MYSQL_PORT_MAGENTO2}:3306"
      networks:
        - backend

### Adminer ###########################################
    adminer:
      image: r.cfcr.io/lanphan/magento2_adminer:1.0
      restart: unless-stopped
      ports:
        - "${ADM_PORT}:8080"
      networks:
        - frontend
        - backend
